version: '3.9'
services:
  db:
    container_name: nusa_db
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
